var sendWayDics = [
    {
        code:"region",
        name:"按区域发送",
        classname:"zl",
        templateUrl:"/fkzl/fkzlSend/region"//切换跳转路由
    },
    {
        code:"org",
        name:"按单位发送",
        classname:"",
        templateUrl:"/fkzl/fkzlSend/org"//切换跳转路由
    },
    {
        code:"person",
        name:"按人员发送",
        classname:"",
        templateUrl:"/fkzl/fkzlSend/person"//切换跳转路由
    }
]